const CVC_DECIMALS = 8;
const ONE_CVC = 10 ** CVC_DECIMALS;
const TOTAL_SUPPLY = 1e9 * ONE_CVC;
const EVENT_ESCROW_PLACED = 'EscrowPlaced';
const EVENT_ESCROW_MOVED = 'EscrowMoved';
const EVENT_ESCROW_RELEASED = 'EscrowReleased';
const EVENT_ESCROW_REFUNDED = 'EscrowCanceled';
const EVENT_CREDENTIAL_ITEM_PRICE_SET = 'CredentialItemPriceSet';
const EVENT_CREDENTIAL_ITEM_PRICE_DELETED = 'CredentialItemPriceDeleted';

module.exports = {
  CVC_DECIMALS,
  ONE_CVC,
  TOTAL_SUPPLY,
  EVENT_ESCROW_PLACED,
  EVENT_ESCROW_MOVED,
  EVENT_ESCROW_RELEASED,
  EVENT_ESCROW_REFUNDED,
  EVENT_CREDENTIAL_ITEM_PRICE_SET,
  EVENT_CREDENTIAL_ITEM_PRICE_DELETED,
};
